language: node_js
node_js:
  - "8"
install:
  - npm i -g angular-cli-ghpages
  - npm i
cache:
  directories:
    - "node_modules"
script:
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
